{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name}}
  labels:
    app: {{ .name}}
    chart: {{ template "api-dyt.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ .type }}
  selector:
    app:  {{ .name}}
    release: {{ $.Release.Name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP

---
{{- end }}