
server:
    enable-self-preservation: false
    port: 8761

management:
  security:
    enabled: false

eureka:
    instance:
        hostname: eureka-server
        preferIpAddress: true
    client:
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8761}/eureka/
    server:
      enable-self-preservation: false